import re
from config.settings import DATABASE_URL, JIRA_URL, JIRA_USERNAME, JIRA_API_TOKEN, JIRA_PROJECT_KEY, JIRA_ISSUE_TYPE, JIRA_LABELS, JIRA_BOARD_ID
import json
import logging
import ast
 
"""
Dummy data feeder to create JIRA tickets
This simulates DB data for now.
"""
import inspect
from connections.database_connections import DatabaseManager
from database.database_operations import insert_jira_ticket_details
from src.plugins.jira_ticketing.notifier import send_teams_notification
from connections.jira_connections import JiraClient
 
 
def build_description(data: dict, rca: dict) -> str:
    """
    Optimized Jira description builder.
    Uses inspect.cleandoc to maintain code readability while producing
    clean, margin-flush output for Jira.
    """
    tool = data.get('error_tool', 'N/A')
    trace = data.get('stack_trace', 'No stack trace available.')
   
    # Extract RCA components
    rca_analysis = rca.get('analysis', 'No analysis available') if isinstance(rca, dict) else str(rca)
    primary_cause = rca.get('primary_cause', 'Unknown') if isinstance(rca, dict) else ''
    contributing_factors = rca.get('contributing_factors', []) if isinstance(rca, dict) else []
   
    # Format contributing factors
    factors_text = ''
    if contributing_factors and isinstance(contributing_factors, list):
        factors_text = '* ' + '\n* '.join(contributing_factors)
   
    return inspect.cleandoc(f"""
        h1. Incident Report
        *Tool/Component:* {tool}
        *Environment:* Production
 
        h2. Root Cause Analysis
        *Primary Cause:* {primary_cause}
       
        *Analysis:*
        {rca_analysis}
       
        h3. Contributing Factors
        {factors_text if factors_text else 'No contributing factors identified'}
 
        h2. Technical Details
        {{code:title=Stack Trace|collapse=true}}
        {trace}
        {{code}}
       
 
        ----
        _Auto-generated by monitoring system._
    """)
 
 
def jira_ticket(incident, rca, db_manager):
    """
    Creates a JIRA ticket with dynamic priority based on AI-generated RCA
    and logs the result to the database.
    """
    try:
 
 
        # 1. Environment Validation
        if not all([JIRA_URL, JIRA_USERNAME, JIRA_API_TOKEN]):
            logging.error("Missing JIRA environment variables.")
            return False
       
        # 2. Initialize Client
        jira_client = JiraClient(JIRA_URL, JIRA_USERNAME, JIRA_API_TOKEN)
       
        # 3. Standardize Incident Data
        incident = {k.lower(): v for k, v in incident.items()}
       
        # 4. Extract Priority Dynamically from RCA
        # Extract severity from RCA dictionary
        final_priority = rca['severity']  # Default priority
 
       
        # 5. Build Content
        summary = f"E:{incident.get('error_id', 'N/A')} | {incident.get('error_message', 'No Message')}"
        description = build_description(incident, rca)
 
        # 6. Create Ticket
        ticket_key = jira_client.create_ticket(
            project_key=JIRA_PROJECT_KEY,
            issue_type=JIRA_ISSUE_TYPE,
            summary=summary,
            description=description,
            priority=final_priority,
            labels = JIRA_LABELS.split(",")  # Default priority, can be overridden by final_priority if needed
        )
 
        # 7. Post-Creation Actions & DB Logging
        if ticket_key:
            logging.info(f"Ticket Created: {ticket_key} with Priority: {final_priority}")
 
 
            # Add automation comment
            jira_client.add_comment(ticket_key, "This ticket was automatically created by the monitoring pipeline.")
           
            # Move from backlog to active sprint and set status to To Do
            if JIRA_BOARD_ID:
                jira_client.move_to_sprint(int(JIRA_BOARD_ID), ticket_key)
                jira_client.transition_ticket(ticket_key, "To Do")
                jira_client.add_comment(ticket_key, "Pulling the ticket form Backlog to the current Sprint")
 
            # Notify Teams
            send_teams_notification(ticket_key, summary)
           
            # Log to Database
            db_success = insert_jira_ticket_details(ticket_key, incident, rca, db_manager)
            return ticket_key if db_success else False
        else:
            logging.error("Ticket creation failed: No key returned from Jira.")
            return False
           
    except Exception as e:
        logging.error(f"Error in jira_ticket workflow: {e}")
        return False
   
def change_ticket_status(ticket_key: str, status: str) -> bool:
    """
    Transitions a Jira ticket to the given status.
 
    Args:
        ticket_key: The Jira ticket key (e.g. 'SCRUM-42').
        status: Target status name (e.g. 'In Progress', 'Done', 'To Do').
 
    Returns:
        True if the transition succeeded, False otherwise.
    """
    if not all([JIRA_URL, JIRA_USERNAME, JIRA_API_TOKEN]):
        logging.error("Missing JIRA environment variables.")
        return False
 
    try:
        jira_client = JiraClient(JIRA_URL, JIRA_USERNAME, JIRA_API_TOKEN)
        success = jira_client.transition_ticket(ticket_key, status)
        if success:
            jira_client.add_comment(ticket_key, f"Status changed to *{status}* by the monitoring pipeline.")
        return success
    except Exception as e:
        logging.error(f"Error in change_ticket_status: {e}")
        return False
 
 
if __name__ == "__main__":
    ticket_key = 'SCRUM-346'
    status = "Done"
    change_ticket_status(ticket_key, status)
    print(f"Ticket ({ticket_key}) status has been updated to {status}")